# Generated by Django 5.0.1 on 2024-03-16 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_alter_booking_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="booked",
                to="booking.room",
            ),
        ),
    ]
